[project]
name = "intersection-delay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datetime>=5.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "tk>=0.1.0",
]
